### ISSUE TITLE
interact.js 1.2.4 drag and gesture action confusion

### ISSUE THREAD

**Issue by jlandt** [taye/interact.js#291]
I have an issue with interact.js 1.2.4 and iPad Retina iOS 8.1 Mobile Safari, which I need to resolve somehow. The problem occurs in a sorting component nested inside a large sequential learning web-application, where the user solves a succession of tasks. The interact.js plugin is used for adding drag/drop behavior so the user can sort elements in the correct order. The site is live, but the issue I'm about to describe is now persistent and reproducible, so it needs to be solved quick.

Here's the setup. We've initialised a number of draggable elements with

   interact('.drag').draggable(...);

and we've registered onstart, onmove and onend listeners, which are handled manually with callback functions.

In most cases, the drag drop behavior acts as planned. But when using the sorting component in certain parts of the application sequence, the actionName of an interaction is inexplicably "gesture" instead of "drag", which makes the validateAction (interact.js) function return null instead of a valid action. This in turn causes the pointerDown (interact.js) handler to never get fired, so the drag motion is never initiated, and the element stays put forever, making it impossible to progress further in the sequence. The behavior only occurs on iPad. If I run the site in an iPad simulator and inspect the element with Safari's developer tools crosshair functionality, something changes the element, and the next interaction's actionName suddenly becomes "drag", so the component starts to work as intended and the user can proceed in the sequence.

Do you have any idea as to:

1. What causes the website to relay a "gesture" action instead of a "drag" action?
2. What excactly happens when I use the inspection crosshair? Why does it change behavior?
3. How do I solve this issue?

You can see the component code here (https://jsfiddle.net/ubLLu4a0/1/), but it's part of a major Backbone solution, so this is all I can include.

Thanks in advance.

**Comment by taye** [comment]
I haven't seen this kind of behaviour before so I can't make much of a guess as to what's going wrong without a demo to reproducing the error. If it's an iPad-specific issue (which I think is unlikely) then I can't debug the error myself since I don't have an iPad.

A few [bugs have been fixed](https://github.com/taye/interact.js/blob/v1.2.6/CHANGELOG.md#126) since v1.2.4. I recommend that you upgrade to v1.2.6 first as some of the fixes relate to gestures and multiple targets.

**Comment by jlandt** [comment]
Thanks a lot for the reply. I will update and see if it solves the issue. To be continued.

**Comment by jlandt** [comment]
Hey again,

We updated to 1.2.6 and the issue is not resolved. Furthermore, the crosshair inspection no longer works, so the actions remain gestures no matter what. Here is a pastebin of the rendered html content on the page: 
http://pastebin.com/98hDHk8W. 
Also, we've been allowed to give access to the site itself. The problematic area can be accessed via deeplink here: 
http://dev.vertic.com/DanskeBank/FinancialLiteracy_v3/?adminId=167659875&devMode=true&missionId=8&taskId=413&lang=da (the site is in Danish). 
Do note, that the issue most likely won't occur when deeplinking (and if so only on iPad), but maybe you can spot something glaringly wrong in the setup of the component, the markup structure, the embedding of the js or maybe even css. The console outputs the actionName on any user action.

Thanks again for responding.

**Comment by taye** [comment]
I think the quickest solution is to use a custom actionChecker that always returns a drag action:

```javascript
interact('.drag').actionChecker(function () {
  return { name: 'drag' };
});
```


The `defaultActionChecker` returns a gesture action if there are 2 or more pointers down. I'll change this in the next version so that the target also needs to be gesturable. Normally it should only be possible for an Interaction to have 2 pointers down if the target Interactable is gesturable. If some code is calling `event.stopPropagation` on a `touchend` event somewhere, that *might* be preventing interact.js from removing pointers from Interactions.

**Comment by jlandt** [comment]
Hey again,

Thanks a lot for the suggested fix. We added it and removed all .stopPropagation() calls, but the component still acts funny. Now, it fails inside the pointerAverage function. It seems to believe there's 6 Touch objects in the pointers array, which makes no sense to me. After the first (semi-succesful and very slow) dragging motion has been completed, the function fails multiple times on the pointers[i][prop] code. The last element in pointers is always undefined. On a positive note, the actionName is always "drag" now.

As before, I'd very much appreciate any guidance you can spare.

**Comment by taye** [comment]
When does the incorrect behaviour start?

Could you try debugging with the following code or similar to see when 
pointers are added/removed?

```javascript
var prevLength = 0;

function idLogger (event) {
   var ids = event.interaction.pointerIds;

   if (/move/.test(event.type) && prevLength === ids.length) {
     return;
   }

   prevLength = ids.length;
   console.log((event.originalEvent || event).type, 'pointerIds: ', ids);
}

interact('.drag').on('dragstart dragend dragmove', idLogger);
interact(document).on('down up move', idLogger);
```

Also maybe remove the other logs for now to keep things clearer. Please 
paste the output of a few buggy drag interactions.

**Comment by jlandt** [comment]
Hey again,

Thank you for the reply, and in turn sorry about the delay - weekend happened. 
Here's your desired debug information:

SORTING DEBUG | idLogger (3)
"touchstart"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499630]


SORTING DEBUG | idLogger (3)
"touchend"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499630]


SORTING DEBUG | idLogger (3)
"touchstart"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499631]


SORTING DEBUG | idLogger (3)
"touchend"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499631]


SORTING DEBUG | idLogger (3)
"touchstart"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499632] 


SORTING DEBUG | _debugTouch | event??? (2)
"touchmove"
[undefined]


SORTING DEBUG | idLogger (3)
"touchmove"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499632]


SORTING DEBUG | idLogger (3)
"touchend"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499632]


SORTING DEBUG | idLogger (3)
"touchstart"
"pointerIds: "
[602499605, 602499615, 602499621, 602499623, 602499633]

etc.

Let me know, if this is sufficient. Thanks for your continued attention to our problem.

**Comment by taye** [comment]
I don't know what's causing multiple pointers to be added but this should remove them:

```javascript
interact(document).on('down', function (event) {
  var interaction = event.interaction;
  var canGesture = interaction.target && interaction.target.options.gesture.enabled;
  var maxAllowedPointers = canGesture? 2 : 1;

  while (interaction.pointers.length > maxAllowedPointers) {
    interaction.removePointer(interaction.pointers[0]);
  }
})

**Comment by jlandt** [comment]
That did the trick! I'll send you a separate e-mail. Thanks!
